version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/app/docker-entrypoint.sh"]
    ports:
      - "80:80"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-laudspeaker}
      - DB_SSL=${DB_SSL:-false}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - MONGODB_URI=${MONGODB_URI}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_CLIENT_ID=${KAFKA_CLIENT_ID}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID}
      - JOURNEY_ONBOARDING=${JOURNEY_ONBOARDING}
      - SYNCHRONIZE=${SYNCHRONIZE}
      - EXTERNAL_URL=${EXTERNAL_URL:-http://localhost:3001}
      - FRONTEND_URL=${EXTERNAL_URL:-http://localhost:3001}
    restart: unless-stopped
    networks:
      - laudspeaker_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  laudspeaker_network:
    driver: bridge
