version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - EXTERNAL_URL=${EXTERNAL_URL:-http://localhost:3001}
        - FRONTEND_SENTRY_AUTH_TOKEN=${FRONTEND_SENTRY_AUTH_TOKEN}
        - BACKEND_SENTRY_AUTH_TOKEN=${BACKEND_SENTRY_AUTH_TOKEN}
        - REACT_APP_POSTHOG_HOST=${REACT_APP_POSTHOG_HOST:-https://app.posthog.com}
        - REACT_APP_POSTHOG_KEY=${REACT_APP_POSTHOG_KEY}
        - REACT_APP_ONBOARDING_API_KEY=${REACT_APP_ONBOARDING_API_KEY}
    ports:
      - "80:80"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - MONGODB_URI=${MONGODB_URI}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_CLIENT_ID=${KAFKA_CLIENT_ID}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID}
      - JOURNEY_ONBOARDING=${JOURNEY_ONBOARDING}
      - SYNCHRONIZE=${SYNCHRONIZE}
      - EXTERNAL_URL=${EXTERNAL_URL:-http://localhost:3001}
      - FRONTEND_URL=${EXTERNAL_URL:-http://localhost:3001}
    restart: unless-stopped
    networks:
      - laudspeaker_network

networks:
  laudspeaker_network:
    driver: bridge
